# Generated by Django 4.2 on 2023-04-21 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Время удаления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=300, null=True, verbose_name='Учебное заведения')),
                ('speciality', models.CharField(max_length=300, null=True, verbose_name='Специальность')),
                ('category_education', models.CharField(choices=[('average', 'Среднее'), ('secondary special', 'Среднее специальное'), ('higher', 'Высшее  образование'), ('master', 'Магистратура'), ('other', 'Другое')], max_length=100, null=True, verbose_name='Категория образования')),
                ('start_date', models.DateField(max_length=100, null=True, verbose_name='Начало обучения')),
                ('finish_date', models.DateField(max_length=100, null=True, verbose_name='Окончание обучения')),
                ('faculty', models.CharField(max_length=200, null=True, verbose_name='Факультет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300, null=True, verbose_name='Название организации')),
                ('start_date', models.DateField(max_length=100, null=True, verbose_name='Начало работы')),
                ('job_title', models.CharField(max_length=300, null=True, verbose_name='Должность')),
                ('end_date', models.DateField(max_length=100, null=True, verbose_name='Окончание работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
        migrations.CreateModel(
            name='VacancyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория вакансии',
                'verbose_name_plural': 'Категории вакансий',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
                ('description', models.TextField(verbose_name='Детальное описание')),
                ('experience_time', models.PositiveIntegerField(verbose_name='Опыт работы (лет)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Опубликовать вакансию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Время удаления')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('vacancy_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='headhunter.vacancycategory', verbose_name='Категория вакансии')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('salary', models.FloatField(verbose_name='Желаемая зарплата')),
                ('info', models.TextField(max_length=3000, verbose_name='Информация о себе')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('telegram', models.CharField(max_length=200, verbose_name='Telegram')),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Linkedin')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать резюме')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Время удаления')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='Автор резюме')),
                ('education', models.ManyToManyField(blank=True, related_name='education', to='headhunter.education', verbose_name='Образование')),
                ('experience', models.ManyToManyField(blank=True, related_name='experience', to='headhunter.experience', verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_or_employer', models.CharField(choices=[('applicant', 'Соискатель'), ('employer', 'Работодатель')], max_length=100, verbose_name='Кто отправитель')),
                ('text', models.TextField(max_length=20000, verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Время удаления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('applicant_employer_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_employer', to='headhunter.applicantemployer', verbose_name='Чат между')),
            ],
        ),
        migrations.AddField(
            model_name='applicantemployer',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='headhunter.resume', verbose_name='Резюме'),
        ),
        migrations.AddField(
            model_name='applicantemployer',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='headhunter.vacancy', verbose_name='Вакансия'),
        ),
    ]
