# Generated by Django 4.2 on 2023-04-20 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headhunter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('salary', models.FloatField(null=True, verbose_name='Желаемая зарплата')),
                ('info', models.TextField(max_length=3000, null=True, verbose_name='Информация о себе')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=12, null=True, verbose_name='Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram')),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Linkedin')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать резюме')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Время удаления')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='Автор резюме')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300, null=True, verbose_name='Название организации')),
                ('start_date', models.DateField(max_length=100, null=True, verbose_name='Начало работы')),
                ('job_title', models.CharField(max_length=300, null=True, verbose_name='Должность')),
                ('end_date', models.DateField(max_length=100, null=True, verbose_name='Окончание работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='headhunter.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=300, null=True, verbose_name='Учебное заведения')),
                ('speciality', models.CharField(max_length=300, null=True, verbose_name='Специальность')),
                ('category_education', models.CharField(choices=[('average', 'Среднее'), ('secondary special', 'Среднее специальное'), ('higher', 'Высшее  образование'), ('master', 'Магистратура'), ('other', 'Другое')], max_length=100, null=True, verbose_name='Категория образования')),
                ('start_date', models.DateField(max_length=100, null=True, verbose_name='Начало обучения')),
                ('finish_date', models.DateField(max_length=100, null=True, verbose_name='Окончание обучения')),
                ('faculty', models.CharField(max_length=200, null=True, verbose_name='Факультет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='headhunter.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
            },
        ),
    ]
